src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserLogin_RazorPages.DomainModel.Entities;

namespace UserLogin_RazorPages.Pages.Account
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public InputModel Input { get; set; } 

        public void OnGet(string returnUrl = null)
        {
            Input = new InputModel();
            Input.ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            const string badUserNameOrPasswordMessage = "Username or password is incorrect.";

            if (string.IsNullOrEmpty(Input.Username)|| string.IsNullOrEmpty(Input.Password))
            {
                return BadRequest(badUserNameOrPasswordMessage);
            }

            var lookupUser = DataAccess.Data.Users.FirstOrDefault(u => u.Username.Equals(Input.Username));

            if (lookupUser?.Password != Input.Password)
            {
                return BadRequest(badUserNameOrPasswordMessage);
            }

            const string Issuer = "https://gov.uk";
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, Input.Username, ClaimValueTypes.String, Issuer),
                new Claim(ClaimTypes.Surname, "Matijevic", ClaimValueTypes.String, Issuer),
                new Claim(ClaimTypes.Country, "CRO", ClaimValueTypes.String, Issuer),
                new Claim(ClaimTypes.Email, "andrej.matijevic@gmail.com", ClaimValueTypes.String, Issuer),
                new Claim("ChildhoodHero", "Michael Jordan", ClaimValueTypes.String)
            };
            var userIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var userPrincipal = new ClaimsPrincipal(userIdentity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, 
                new ClaimsPrincipal(userPrincipal));

            if (Input.ReturnUrl == null)
            {
                Input.ReturnUrl = TempData["returnUrl"]?.ToString();
            }

            if (Input.ReturnUrl != null)
            {
                return Redirect(Input.ReturnUrl);
            }

            return RedirectToPage("/Index");

        }

        public class InputModel
        {
            public string Username { get; set; }
            public string Password { get; set; }
            public string ReturnUrl { get; set; }
        }
    }
}

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UserLogin_RazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UserLogin_RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        public DateTime Date { get; set; }
        public List<DomainModel.Entities.Playground> Playgrounds { get; set; }
       

        public void OnGet()
        {
            Date = DateTime.Now.Date;
            Playgrounds = DataAccess.Data.Playgrounds;
        }

    }
}

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Playground/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UserLogin_RazorPages.Pages.Playground
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnGetAssignAsync(int id)
        {
            //await _userService.ResetDisplayName(User);
            if (User != null)
            {
                var playground = DataAccess.Data.Playgrounds.FirstOrDefault(p => p.Id == id);
                playground.Users.Add(new DomainModel.Entities.User { Email = "Bla" });
            }

            return RedirectToPage("/Index");
        }
    }
}

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UserLogin_RazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Account/Login.cshtml
@page
@model UserLogin_RazorPages.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Login</h1>

<form method="post" asp-page="/Account/Login" >
    <input hidden asp-for="Input.ReturnUrl"/>
    <input asp-for="Input.Username" /><br />
    <input asp-for="Input.Password" /><br />
    <button>Submit</button>
</form>

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page Changed";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>@Model.Date.ToShortDateString()</p>
    @foreach (var playground in Model.Playgrounds)
    {
        <div>
            <p>@playground.Name</p>
            <p>@playground?.Users?.Count</p>
            <p>@playground.StartTime</p>

            <a asp-page="/Playground/Index" asp-page-handler="Assign" asp-route-id="@playground.Id">I want to play</a>
            @* This is visible only if user is already assign for that playeground and login  *@
            @*<a asp-page="/Index" asp-page-handler="UnAssign" asp-route-id="@playground.PlaygroundName">I don't want to play</a>*@
        </div>
    }
</div>

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Playground/Index.cshtml
@page
@model UserLogin_RazorPages.Pages.Playground.IndexModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Index</h1>

src/UserLogin_RazorPages/UserLogin_RazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserLogin_RazorPages</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Logo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - UserLogin_RazorPages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>